# Generated by Django 4.2.4 on 2023-08-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_img_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='rep_url',
            field=models.URLField(blank=True),
        ),
    ]
