# Generated by Django 4.2.4 on 2023-08-25 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_rep_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='url',
            new_name='demo_url',
        ),
    ]
